export const availableComponents = [
  "button",
  "card",
  "badge",
  "input",
  "textarea",
  "tabs",
  "popover",
  "form",
  "drawer",
  "dialog",
  "checkbox",
  "alert",
  "alert-dialog",
  "avatar",
  "breadcrumb",
  "calendar",
  "combobox",
  "command",
  "collapsible",
  "data-table",
  "toast",
  "label",
  "pagination",
  "navbar",
  "input-otp",
];

export const componentImports = {
  button: 'import { Button } from "@/components/ui/button";',
  card: `import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";`,
  badge: 'import { Badge } from "@/components/ui/badge";',
  input: 'import { Input } from "@/components/ui/input";',
  textarea: 'import { Textarea } from "@/components/ui/textarea";',
  tabs: `import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";`,
  popover: `import { Popover, PopoverClose, PopoverContent, PopoverDescription, PopoverHeader, PopoverTitle, PopoverTrigger } from "@/components/ui/popover";`,
  form: `import { Form, FormActions, FormControl, FormDescription, FormField, FormLabel, FormMessage, FormSection, FormSectionDescription, FormSectionHeader, FormSectionTitle } from "@/components/ui/form";`,
  drawer: `import {
  Drawer,
  DrawerBody,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/ui/drawer";`,
  dialog: `import {
  Dialog,
  DialogBody,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";`,
  checkbox: 'import { Checkbox } from "@/components/ui/checkbox";',
  alert: `import {
  Alert,
  AlertActions,
  AlertDescription,
  AlertTitle,
} from "@/components/ui/alert";`,
  "alert-dialog": `import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";`,
  avatar: `import {
  Avatar,
  AvatarFallback,
  AvatarGroup,
  AvatarGroupCount,
  AvatarImage,
  AvatarStatus,
} from "@/components/ui/avatar";`,
  breadcrumb: `import {
  Breadcrumb,
  BreadcrumbEllipsis,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";`,

  calendar:
    'import { Calendar } from "@/components/ui/calendar";',
  combobox: `import {
  Combobox,
  ComboboxClear,
  ComboboxEmpty,
  ComboboxInput,
  ComboboxInputGroup,
  ComboboxItem,
  ComboboxItemIndicator,
  ComboboxList,
  ComboboxPopup,
  ComboboxPortal,
  ComboboxPositioner,
  ComboboxTrigger,
} from "@/components/ui/combobox";`,

  command: `import {
  Command,
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandLoading,
  CommandSeparator,
  CommandShortcut,
} from "@/components/ui/command";`,

  collapsible: `import {
  Collapsible,
  CollapsibleContent,
  CollapsiblePanel,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";`,

  "data-table": `import {
  DataTable,
  DataTableColumnHeader,
  DataTableColumnVisibility,
  DataTablePagination,
  DataTableSelectAll,
  DataTableSelectRow,
  DataTableSortButton,
} from "@/components/ui/data-table";`,

toast: `import {
  ToastProvider,
  Toaster,
  useToast,
} from "@/components/ui/toast";`,

label: `import {
  Label,
  LabelOptional,
  LabelRequired,
} from "@/components/ui/label";`,

navbar: `import {
  Navbar,
  NavbarActions,
  NavbarBrand,
  NavbarContainer,
  NavbarLink,
  NavbarMenuButton,
  NavbarMobileLink,
  NavbarMobileMenu,
  NavbarNav,
} from "@/components/ui/navbar";`,

pagination: `import {
  Pagination,
  PaginationButton,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";`,

  "input-otp": `import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
  InputOTPSeparator,
} from "@/components/ui/input-otp";`,

};
